"""
models.py - Pydantic Data Models

All structured data types used across the agent.
Every analysis result is validated through these
models before being displayed or saved.
"""

from pydantic import BaseModel
from typing import Any


class CSVSchema(BaseModel):
    """
    Describes the structure of an uploaded CSV file.
    Generated by the analyzer before sending to Groq.
    """
    filename:    str
    rows:        int
    columns:     list[str]
    dtypes:      dict[str, str]
    sample_data: str          # first 3 rows as string, sent to Groq for context


class GeneratedCode(BaseModel):
    """
    The pandas code generated by Groq to answer the question.
    Validated before execution.
    """
    question:   str
    code:       str
    explanation: str          # what the code does, in plain English


class ExecutionResult(BaseModel):
    """
    The result of running the generated code in the sandbox.
    success=False means the code errored or timed out.
    """
    success:     bool
    output:      str          # stdout from the subprocess
    error:       str | None   # stderr if it failed
    output_type: str          # "table", "number", "text", or "chart"


class AnalysisReport(BaseModel): 
    """
    The full report for one analysis run.
    Combines the question, code, result, and narrative.
    """
    question:    str
    code:        str
    result:      str
    narrative:   str          # Groq's plain English explanation
    chart_path:  str | None   # path to saved chart image if generated
    success:     bool