"""
report_builder.py - Markdown Report Generator

Combines the question, generated code, result,
chart, and narrative into a downloadable markdown report.
Report is saved with a timestamp in the reports/ folder.
"""

import os
from datetime import datetime
from models import AnalysisReport


REPORTS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "reports")

def ensure_reports_dir():
    os.makedirs(REPORTS_DIR, exist_ok=True)


def build_report(report: AnalysisReport) -> str:

    timestamp = datetime.now().strftime("%d %B %Y at %H:%M")

    sections = [
        f"# Data Analysis Report",
        f"Generated on {timestamp}",
        f"",
        f"## Question",
        f"{report.question}",
        f"",
        f"## Answer",
        f"{report.narrative}",
        f"",
        f"## Raw Result",
        f"```",
        f"{report.result}",
        f"```",
        f"",
        f"## Generated Code",
        f"```python",
        f"{report.code}",
        f"```",
    ]

    if report.chart_path:
        sections += [
            f"",
            f"## Chart",
            f"Chart saved to: {report.chart_path}",
        ]

    sections += [
        f"",
        f"---",
        f"*Generated by Data Analysis Agent*"
    ]

    return "\n".join(sections)


def save_report(report: AnalysisReport) -> str:

    ensure_reports_dir()

    timestamp   = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_path = os.path.join(REPORTS_DIR, f"report_{timestamp}.md")
    content     = build_report(report)

    with open(report_path, "w", encoding="utf-8") as f:
        f.write(content)

    return report_path