"""
Lab 5.3 — Consensus Engine

Build a 4-agent system where three specialist agents independently answer
the same question and a Consensus Agent combines their responses using
confidence-weighted voting. If no answer achieves at least 60% weighted
confidence, the top two most confident agents perform a second review
after seeing each other's reasoning. The final result always includes a
dissent summary to highlight any remaining disagreements.
"""

import json
import operator
import os
import sys
import time
from typing import Annotated, List, Optional, TypedDict

from pydantic import BaseModel, Field, ValidationError
from langgraph.graph import StateGraph, START, END

from dotenv import load_dotenv

load_dotenv()  


#class definitions for the structured data used in the consensus engine
#this class defines the structure of the data that will be passed between the agents and the consensus engine
class AgentOpinion(BaseModel):
    agent_name: str
    answer: str = Field(..., description="The agent's full answer/position")
    answer_key: str = Field(
        ..., description="Short normalized phrase (<=5 words, lowercase) used to "
                          "group equivalent answers together for voting, e.g. 'yes', "
                          "'use microservices', '42'"
    )
    confidence: float = Field(..., ge=0.0, le=1.0)
    reasoning: str

#this class defines the structure of the disagreement notes that will be generated by the consensus engine
class DissentNote(BaseModel):
    agents_involved: List[str]
    description: str

#this class defines the structure of the final result that will be returned by the consensus engine
class ConsensusResult(BaseModel):
    question: str
    final_answer: str
    weighted_confidence: float = Field(..., ge=0.0, le=1.0)
    rounds_used: int
    all_opinions: List[AgentOpinion]
    dissent_summary: Optional[str] = None
    dissent_notes: List[DissentNote] = Field(default_factory=list)

#this class defines the structure of the dissent output that will be generated by the consensus engine
class _DissentOutput(BaseModel):
    dissent_summary: str
    dissent_notes: List[DissentNote] = Field(default_factory=list)


#llm call

DEFAULT_MODEL = os.environ.get("GROQ_MODEL", "llama-3.3-70b-versatile")
_client = None


def get_client():
    global _client
    if _client is None:
        from groq import Groq
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            raise RuntimeError("GROQ_API_KEY not set. `export GROQ_API_KEY=...` first.")
        _client = Groq(api_key=api_key)
    return _client


def structured_completion(system_prompt: str, user_prompt: str, schema, max_retries: int = 2):
    client = get_client()
    schema_hint = json.dumps(schema.model_json_schema(), indent=2)
    full_system = (
        f"{system_prompt}\n\nRespond with a single valid JSON object matching this schema "
        f"and nothing else (no markdown fences, no preamble):\n{schema_hint}"
    )
    last_error = None
    for attempt in range(max_retries + 1):
        try:
            response = client.chat.completions.create(
                model=DEFAULT_MODEL,
                messages=[{"role": "system", "content": full_system},
                          {"role": "user", "content": user_prompt}],
                response_format={"type": "json_object"},
                temperature=0.4,
            )
            data = json.loads(response.choices[0].message.content)
            return schema.model_validate(data)
        except (json.JSONDecodeError, ValidationError, Exception) as e:  # noqa: BLE001
            last_error = e
            if attempt < max_retries:
                time.sleep(0.5 * (attempt + 1))
                continue
            raise RuntimeError(f"LLM call failed after {max_retries + 1} attempts: {last_error}")


#agents

AGENT_PERSONAS = {
    "AnalyticalAgent": (
        "You are a rigorous analytical thinker. Answer using first-principles "
        "reasoning and structured logic. Be willing to say 'it depends' with "
        "explicit conditions rather than force a false certainty."
    ),
    "PragmaticAgent": (
        "You are a pragmatic, experience-driven advisor. Answer based on what "
        "typically works in practice, drawing on analogous real-world situations, "
        "even if it's not the theoretically 'purest' answer."
    ),
    "SkepticalAgent": (
        "You are a deliberately skeptical devil's advocate. Actively look for "
        "reasons the obvious answer might be wrong, hidden assumptions, or "
        "edge cases others would miss. Don't disagree for its own sake — only "
        "when you have a real reason."
    ),
}


def ask_agent(agent_name: str, question: str, extra_context: str = "") -> AgentOpinion:
    persona = AGENT_PERSONAS[agent_name]
    system_prompt = (
        f"{persona}\n\nProvide your answer, a normalized answer_key for grouping, "
        "your confidence (0-1) reflecting how sure you genuinely are, and your reasoning."
    )
    user_prompt = f"Question: {question}"
    if extra_context:
        user_prompt += f"\n\n{extra_context}"

    opinion = structured_completion(system_prompt, user_prompt, AgentOpinion)
    opinion.agent_name = agent_name
    return opinion


#consensus agent

CONSENSUS_THRESHOLD = 0.60


def weighted_vote(opinions: List[AgentOpinion]) -> tuple:
    """Returns (winning_answer_key, representative_answer_text, weighted_share)."""
    total_confidence = sum(o.confidence for o in opinions) or 1e-6
    scores: dict = {}
    for o in opinions:
        key = o.answer_key.strip().lower()
        scores[key] = scores.get(key, 0.0) + o.confidence

    best_key, best_score = max(scores.items(), key=lambda kv: kv[1])
    share = round(best_score / total_confidence, 3)

    # Representative full-text answer = highest-confidence opinion within the winning group
    candidates = [o for o in opinions if o.answer_key.strip().lower() == best_key]
    representative = max(candidates, key=lambda o: o.confidence)

    return best_key, representative.answer, share


def build_dissent_summary(question: str, opinions: List[AgentOpinion]) -> _DissentOutput:
    keys = {o.answer_key.strip().lower() for o in opinions}
    if len(keys) <= 1:
        return _DissentOutput(dissent_summary="", dissent_notes=[])

    opinions_blob = "\n\n".join(
        f"### {o.agent_name} (confidence={o.confidence})\nAnswer: {o.answer}\nReasoning: {o.reasoning}"
        for o in opinions
    )
    system_prompt = (
        "You are the Consensus Agent. The specialist agents below disagreed on the "
        f"question: '{question}'. Write a short, honest dissent summary explaining "
        "what they disagreed about and why — do not paper over the disagreement. "
        "Also produce structured dissent notes naming which agents are in conflict."
    )
    return structured_completion(system_prompt, opinions_blob, _DissentOutput)


#main built of langgraph


class ConsensusState(TypedDict):
    question: str
    round1_opinions: Annotated[List[AgentOpinion], operator.add]
    final_opinions: List[AgentOpinion]
    rounds_used: int
    result: Optional[ConsensusResult]


def _round1_node(agent_name: str):
    def node(state: ConsensusState) -> dict:
        return {"round1_opinions": [ask_agent(agent_name, state["question"])]}
    return node


def _router_node(state: ConsensusState) -> dict:
    # Default: assume round 1 is final unless the conditional edge routes to second_round
    return {"final_opinions": list(state["round1_opinions"]), "rounds_used": 1}


def _route_after_round1(state: ConsensusState) -> str:
    _, _, share = weighted_vote(state["round1_opinions"])
    return "finalize" if share >= CONSENSUS_THRESHOLD else "second_round"


def _second_round_node(state: ConsensusState) -> dict:
    round1 = state["round1_opinions"]
    top2 = sorted(round1, key=lambda o: o.confidence, reverse=True)[:2]
    top2_names = {o.agent_name for o in top2}

    context = "Round 1 opinions from all agents:\n" + "\n".join(
        f"- {o.agent_name} (confidence={o.confidence}): {o.answer} — {o.reasoning}"
        for o in round1
    ) + (
        "\n\nYou were one of the two highest-confidence agents. Weighted consensus "
        "was NOT reached in round 1. Reconsider your answer in light of the other "
        "agents' reasoning above. You may keep your answer or revise it — be honest."
    )

    revised = [ask_agent(o.agent_name, state["question"], extra_context=context) for o in top2]

    unchanged = [o for o in round1 if o.agent_name not in top2_names]
    final_opinions = revised + unchanged
    return {"final_opinions": final_opinions, "rounds_used": 2}


def _finalize_node(state: ConsensusState) -> dict:
    opinions = state["final_opinions"]
    best_key, final_answer, share = weighted_vote(opinions)
    dissent = build_dissent_summary(state["question"], opinions)

    result = ConsensusResult(
        question=state["question"],
        final_answer=final_answer,
        weighted_confidence=share,
        rounds_used=state["rounds_used"],
        all_opinions=opinions,
        dissent_summary=dissent.dissent_summary or None,
        dissent_notes=dissent.dissent_notes,
    )
    return {"result": result}


def build_graph():
    graph = StateGraph(ConsensusState)

    graph.add_node("analytical", _round1_node("AnalyticalAgent"))
    graph.add_node("pragmatic", _round1_node("PragmaticAgent"))
    graph.add_node("skeptical", _round1_node("SkepticalAgent"))
    graph.add_node("router", _router_node)
    graph.add_node("second_round", _second_round_node)
    graph.add_node("finalize", _finalize_node)

    for agent_node in ("analytical", "pragmatic", "skeptical"):
        graph.add_edge(START, agent_node)
        graph.add_edge(agent_node, "router")

    graph.add_conditional_edges(
        "router", _route_after_round1, {"finalize": "finalize", "second_round": "second_round"}
    )
    graph.add_edge("second_round", "finalize")
    graph.add_edge("finalize", END)

    return graph.compile()


def run_consensus(question: str) -> ConsensusResult:
    app = build_graph()
    final_state = app.invoke({
        "question": question, "round1_opinions": [], "final_opinions": [],
        "rounds_used": 0, "result": None,
    })
    return final_state["result"]


#cli reporting


def print_report(result: ConsensusResult) -> None:
    print()
    print("CONSENSUS ENGINE REPORT")
    print()
    print(f"\nQuestion: {result.question}")
    print(f"Rounds used: {result.rounds_used} \n")

    for o in result.all_opinions:
        print(f"── {o.agent_name} " + "─" * max(1, 40 - len(o.agent_name)))
        print(f"   Answer: {o.answer}")
        print(f"   Confidence: {o.confidence}")
        print(f"   Reasoning: {o.reasoning}\n")

    print()
    print("FINAL CONSENSUS")
    print()
    print(f"Answer: {result.final_answer}")
    print(f"Weighted confidence: {result.weighted_confidence}")

    if result.dissent_summary:
        print(f"\n DISSENT SUMMARY:\n{result.dissent_summary}")
        for note in result.dissent_notes:
            print(f"\n   Conflict between: {', '.join(note.agents_involved)}")
            print(f"   {note.description}")
    else:
        print("\nFull agreement — no dissent to report.")
    print()


def main():
    question = input("Enter your question: ")

    result = run_consensus(question)
    print_report(result)

if __name__ == "__main__":
    main()